
name: openwrt-build-github-actions

# 4C/16GRAM/14GSSD
# whoami => runner
# pwd => /home/runner/work/openwrt-custom-build/openwrt-custom-build
# docker whoami => root
# docker pwd => /github/workspace

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  targets:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      version: ${{ steps.set-matrix.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: set-matrix
        id: set-matrix
        run: |
          targets=$(sed -e '/^#/d' -e '/^$/d' -e 's/^[[:space:]]*//' -e 's/[[:space:]]*,*$//' targets.txt | jq -R . | jq -sc .)
          echo "matrix={\"target\":$targets}" >> $GITHUB_OUTPUT
          echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT

  build:
    needs: targets
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.targets.outputs.matrix) }}
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: clean-system
        run: |
          df -h
          sudo apt-get autoremove --purge
          sudo apt-get clean
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          df -h
      - name: build-targets
        id: build-step
        uses: docker://ubuntu:24.04
        with:
          entrypoint: /bin/bash
          args: |
            -c "
            apt update
            apt upgrade -y
            apt install -y tree build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
            apt-get autoremove --purge
            apt-get clean
            useradd -u $(stat -c '%u' $GITHUB_WORKSPACE) -M -s /bin/bash runner
            runuser -u runner -- bash ./build.sh '${{ needs.targets.outputs.version }}' '${{ matrix.target }}'
            "
      - name: summary-information
        run: |
          tree -L 3 openwrt/bin/targets
          ls -l bin
          df -h
          tmp=${{ matrix.target }}
          echo "ARTIFACT_NAME=${tmp##*/}" >> $GITHUB_ENV
      - name: upload-artifact
        if: steps.build-step.conclusion == 'success'
        uses: actions/upload-artifact@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: bin/*-squashfs-sysupgrade.bin
          retention-days: 3

  release:
    runs-on: ubuntu-latest
    needs: [targets, build]
    if: github.ref_type == 'tag'
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v8
        with:
          path: bin
      - name: summary
        run: |
          tree -L 3 bin
          find bin -mindepth 2 -type f -name "*-squashfs-sysupgrade.bin" -exec cp -f {} bin/ \;
          ls -l bin
      - name: create-release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{ needs.targets.outputs.version }}
          body_path: version.txt
          draft: false
          prerelease: false
          files: bin/*-squashfs-sysupgrade.bin
      - name: delete-workflow-runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 5
